name: CI

on:
  push:
  pull_request:
  release:

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure project
        run: cmake -B build-msvc -G "Visual Studio 16 2019" -A x64

      - name: Build project
        run: cmake --build ./build-msvc --config Release

      - name: Archive 
        uses: actions/upload-artifact@v1.0.0
        with:
          name: process-image.exe
          path: '${{ github.workspace }}/build-msvc/Release/process-image.exe'